name: Simple Release Workflow

on:
  release:
    types: [published]

jobs:
  echo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "A new release has been published!"
